### ISSUE TITLE
Quyền lấy dữ liệu

### ISSUE THREAD

**Issue by huynhhoanghuy** [tuandoan998/DS_Final_Project#1]
Chào bạn, mình là Huỳnh Hoàng Huy của nhóm 4, mình thấy project nhóm bạn có 2 vấn đề sau:
#1) Mình khuyến nghị khi lấy dữ liệu nên giới hạn trong 1 khoảng thời gian (vì đề bài yêu cầu là thầy sẽ chạy lại nên có thể khi đó dữ liệu đã thay đổi).
#2) Nhóm mình trước đây đặt câu hỏi tương tự nhóm bạn: Dựa vào mô tả để phân thể loại phim, sau đấy thì nhóm mình bị reject. Nên mình nghĩ bạn nên hỏi thầy lại đề tài có hợp lý không.
#3) Mình nghĩ các bạn nên kiểm tra lại file robots.txt. Vì sau khi xem xét mình thấy có vấn đề:
Trong file "GetUrls.ipynb" các bạn có sử dụng lệnh này: 
         **browser.get(f'https://www.bbc.co.uk/search?q={keyword}&filter={bbc_filter}')**
Tuy nhiên, theo https://www.bbc.com/robots.txt có chứa nội dung sau:
Disallow: /search/
Disallow: /search$
Disallow: /search?

Mình đã thử check lại bằng một tool online và thấy việc crawl này không hợp lệ:
*https://technicalseo.com/tools/robots-txt/*

**Comment by tuandoan998** [comment]
Chào bạn,
Đầu tiên nhóm mình xin cảm ơn về sự góp ý chi tiết của bạn.
Về vấn đề số 3, nhóm mình dùng đoạn code như trong slide để kiểm tra tính hợp lệ của dữ liệu thu thập.
![Screenshot from 2019-12-11 21-37-32](https://user-images.githubusercontent.com/26211567/70633391-15b8e400-1c63-11ea-84cf-792dc6b527c6.png)
Mình sẽ hỏi Thầy về vấn đề này.

**Comment by KienTrann** [comment]
@tuandoan998: Có vẻ `robotparser` chạy không đúng. Mình thử  `print(rp)` sau câu lệnh `rp.read()` thì ra rỗng; trong khi đó, mình thử với một số trang khác thì thấy in ra được (em có thể thử). Lý do có thể là như này: theo [document](https://docs.python.org/3/library/urllib.robotparser.html) thì `robotparser` parse file robots.txt theo qui ước [ở đây](https://www.robotstxt.org/orig.html); đây có vẻ là qui ước đơn giản, chỉ có từ "User-agent" và "Disallow", trong khi đó, ở trang bbc có từ "Sitemap" --> làm `robotparser` không parse được?

Mình nghĩ để chắc chắn thì nên kiểm tra thủ công (cũng không tốn nhiều thời gian), chứ không trông cậy vào `robotparser` nữa. Hoặc không thì kiếm một công cụ kiểm tra khác tốt hơn.

Cảm ơn bạn @huynhhoanghuy đã chỉ ra vấn đề này.

**Comment by trqminh** [comment]
Về vấn đề 2 mà bạn góp ý:
#2) Mình nghĩ 2 chủ đề là khác nhau, theo mình, nếu nội dung của nhóm bạn là phân loại thể loại phim dựa trên nội dung phim thì khi đó mới giống nhóm mình (phân loại thể loại văn bản dựa trên nội dung văn bản).
