### ISSUE TITLE
Nhóm 4- góp ý lần 2

### ISSUE THREAD

**Issue by vietph34** [tuandoan998/DS_Final_Project#3]
Chào các bạn,
Sau khi xem file notebooks các bạn dùng trong việc phân lớp, mình thấy kết quả khá tốt tuy nhiên trong confuse matrix vẫn còn một số lớp bị gán nhãn sai. Nhóm bạn đã có cách nào để giải quyết trường hợp này chưa?

**Comment by trqminh** [comment]
Nhóm mình vẫn đang suy nghĩ thêm, cảm ơn bạn đã góp ý
