### ISSUE TITLE
Nhóm 4 góp ý: Chọn đặc trưng và tiền xử lý

### ISSUE THREAD

**Issue by huynhhoanghuy** [tuandoan998/DS_Final_Project#4]
Chào bạn, mình có vài góp ý:
1. Mình kiếm không thấy hàm check xem có bị missing value hay không. Liệu rằng nếu gặp phải trường hợp đó code bạn có chạy ổn?
2. Mình băng khoăn 2 đặc trưng sau: Số lượng dấu cảm thán (!, ?), Số chữ cái viết hoa. Có nên chọn hay không? Tại sao bạn có đoạn lower() rồi thì xét chữ cái viết hoa chi nữa.
3. Bạn nên chú thích plot.

**Comment by trqminh** [comment]
1. Nhóm mình sẽ thực hiện thêm phần này
2. Trong quá trình thử nghiệm, mình thấy có những sự thay đổi độ chính xác với khi có thêm các đặc trưng này, mình sẽ cố gắng làm rõ hơn, còn về phần lower() chỉ nằm trong pipeline của tfidf nên ko ảnh hưởng.
3. Mình sẽ chú thích kĩ hơn
Cảm ơn các ý kiến của bạn nhiều (y)

**Comment by KienTrann** [comment]
@tuandoan998 @trqminh Nhóm em up slide lên nha.

**Comment by tuandoan998** [comment]
Thưa thầy @KienTran89, ngày mai các nhóm lên vấn đáp đúng theo giờ của lịch vấn đáp đúng không ạ?
Nhóm em đã cập nhật slide rồi ạ.
